import type { Exercise } from '../types';

export const exerciseLibrary: Exercise[] = [
  {
    id: 'ex-001',
    name: 'Chin Tuck Retraction',
    instruction: 'Pull chin straight back creating a double chin. Hold 5 seconds.',
    reps: '3×15',
    durationSeconds: 120,
    scorePoints: 4,
    targets: ['forward_head'],
    gifUrl: '/assets/exercises/chin-tuck.gif',
  },
  {
    id: 'ex-002',
    name: 'Neck Flexor Stretch',
    instruction: 'Tilt head to one side, hold ear toward shoulder for 30 seconds each side.',
    reps: '2×30s',
    durationSeconds: 120,
    scorePoints: 3,
    targets: ['forward_head'],
    gifUrl: '/assets/exercises/neck-flexor.gif',
  },
  {
    id: 'ex-003',
    name: 'Wall Angels',
    instruction: 'Stand with back flat against wall, slide arms up and down.',
    reps: '3×12',
    durationSeconds: 150,
    scorePoints: 6,
    targets: ['rounded_shoulders', 'forward_head'],
    gifUrl: '/assets/exercises/wall-angels.gif',
  },
  {
    id: 'ex-004',
    name: 'Doorway Chest Stretch',
    instruction: 'Place forearms on door frame edges, lean forward gently.',
    reps: '3×30s',
    durationSeconds: 90,
    scorePoints: 4,
    targets: ['rounded_shoulders'],
    gifUrl: '/assets/exercises/doorway-stretch.gif',
  },
  {
    id: 'ex-005',
    name: 'Band Pull-Apart',
    instruction: 'Hold resistance band at shoulder width, pull apart squeezing shoulder blades.',
    reps: '3×15',
    durationSeconds: 120,
    scorePoints: 5,
    targets: ['rounded_shoulders'],
    gifUrl: '/assets/exercises/band-pull-apart.gif',
  },
  {
    id: 'ex-006',
    name: 'Prone Y Raise',
    instruction: 'Lie face down, raise arms in Y position squeezing upper back.',
    reps: '3×12',
    durationSeconds: 120,
    scorePoints: 5,
    targets: ['rounded_shoulders'],
    gifUrl: '/assets/exercises/prone-y-raise.gif',
  },
  {
    id: 'ex-007',
    name: 'Hip Flexor Lunge Stretch',
    instruction: 'Kneel with one foot forward, push hips forward gently.',
    reps: '2×30s each side',
    durationSeconds: 120,
    scorePoints: 4,
    targets: ['pelvic_tilt'],
    gifUrl: '/assets/exercises/hip-flexor-lunge.gif',
  },
  {
    id: 'ex-008',
    name: 'Glute Bridge',
    instruction: 'Lie on back with knees bent, lift hips squeezing glutes at top.',
    reps: '3×15',
    durationSeconds: 120,
    scorePoints: 5,
    targets: ['pelvic_tilt'],
    gifUrl: '/assets/exercises/glute-bridge.gif',
  },
  {
    id: 'ex-009',
    name: 'Dead Bug',
    instruction: 'Lie on back, extend opposite arm and leg while keeping lower back flat.',
    reps: '3×10 each side',
    durationSeconds: 150,
    scorePoints: 6,
    targets: ['pelvic_tilt'],
    gifUrl: '/assets/exercises/dead-bug.gif',
  },
  {
    id: 'ex-010',
    name: 'Cat-Cow Stretch',
    instruction: 'On hands and knees, alternate between arching and rounding the spine.',
    reps: '3×10',
    durationSeconds: 90,
    scorePoints: 3,
    targets: ['pelvic_tilt', 'rounded_shoulders'],
    gifUrl: '/assets/exercises/cat-cow.gif',
  },
  {
    id: 'ex-011',
    name: 'Thoracic Extension on Foam Roller',
    instruction: 'Lie on foam roller across upper back, extend over it gently.',
    reps: '3×10',
    durationSeconds: 120,
    scorePoints: 5,
    targets: ['rounded_shoulders'],
    gifUrl: '/assets/exercises/thoracic-extension.gif',
  },
  {
    id: 'ex-012',
    name: 'Scapular Squeeze',
    instruction: 'Sit upright, squeeze shoulder blades together and hold for 5 seconds.',
    reps: '3×15',
    durationSeconds: 90,
    scorePoints: 4,
    targets: ['rounded_shoulders'],
    gifUrl: '/assets/exercises/scapular-squeeze.gif',
  },
  {
    id: 'ex-013',
    name: 'Seated Neck Retraction',
    instruction: 'While seated, pull head straight back without tilting, hold 3 seconds.',
    reps: '3×12',
    durationSeconds: 90,
    scorePoints: 3,
    targets: ['forward_head'],
    gifUrl: '/assets/exercises/seated-neck-retraction.gif',
  },
  {
    id: 'ex-014',
    name: 'Supine Pelvic Tilt',
    instruction: 'Lie on back, flatten lower back against floor by tilting pelvis.',
    reps: '3×15',
    durationSeconds: 90,
    scorePoints: 4,
    targets: ['pelvic_tilt'],
    gifUrl: '/assets/exercises/supine-pelvic-tilt.gif',
  },
  {
    id: 'ex-015',
    name: 'Suboccipital Release',
    instruction: 'Place two fingers at base of skull, apply gentle pressure and nod.',
    reps: '2×60s',
    durationSeconds: 120,
    scorePoints: 3,
    targets: ['forward_head'],
    gifUrl: '/assets/exercises/suboccipital-release.gif',
  },
  {
    id: 'ex-016',
    name: 'Pigeon Stretch',
    instruction: 'From all fours, bring one knee forward and extend other leg back.',
    reps: '2×45s each side',
    durationSeconds: 180,
    scorePoints: 5,
    targets: ['pelvic_tilt'],
    gifUrl: '/assets/exercises/pigeon-stretch.gif',
  },
  {
    id: 'ex-017',
    name: 'Face Pull (Band)',
    instruction: 'Pull resistance band to face level with elbows high.',
    reps: '3×15',
    durationSeconds: 120,
    scorePoints: 5,
    targets: ['rounded_shoulders', 'forward_head'],
    gifUrl: '/assets/exercises/face-pull.gif',
  },
  {
    id: 'ex-018',
    name: 'Standing Chest Opener',
    instruction: 'Clasp hands behind back, lift arms while squeezing shoulder blades.',
    reps: '3×15s hold',
    durationSeconds: 90,
    scorePoints: 3,
    targets: ['rounded_shoulders'],
    gifUrl: '/assets/exercises/chest-opener.gif',
  },
  {
    id: 'ex-019',
    name: 'Quadruped Arm/Leg Raise',
    instruction: 'On hands and knees, extend opposite arm and leg, hold 5 seconds.',
    reps: '3×10 each side',
    durationSeconds: 150,
    scorePoints: 5,
    targets: ['pelvic_tilt', 'rounded_shoulders'],
    gifUrl: '/assets/exercises/quadruped-raise.gif',
  },
  {
    id: 'ex-020',
    name: 'Upper Trapezius Stretch',
    instruction: 'Tilt head to side, gently pull with hand for deeper stretch.',
    reps: '2×30s each side',
    durationSeconds: 120,
    scorePoints: 3,
    targets: ['forward_head', 'rounded_shoulders'],
    gifUrl: '/assets/exercises/upper-trap-stretch.gif',
  },
  {
    id: 'ex-021',
    name: 'Thread the Needle',
    instruction: 'From all fours, reach one arm under body rotating thoracic spine.',
    reps: '3×10 each side',
    durationSeconds: 150,
    scorePoints: 5,
    targets: ['rounded_shoulders'],
    gifUrl: '/assets/exercises/thread-needle.gif',
  },
  {
    id: 'ex-022',
    name: 'Standing Hip Flexor Stretch',
    instruction: 'Step forward into lunge, push hips forward keeping torso upright.',
    reps: '2×30s each side',
    durationSeconds: 120,
    scorePoints: 4,
    targets: ['pelvic_tilt'],
    gifUrl: '/assets/exercises/standing-hip-flexor.gif',
  },
  {
    id: 'ex-023',
    name: 'Bruegger Relief Position',
    instruction: 'Sit at edge of chair, spread knees, turn palms up, squeeze shoulders back.',
    reps: '5×10s hold',
    durationSeconds: 60,
    scorePoints: 3,
    targets: ['rounded_shoulders', 'forward_head'],
    gifUrl: '/assets/exercises/bruegger.gif',
  },
  {
    id: 'ex-024',
    name: 'Towel Neck Stretch',
    instruction: 'Wrap towel behind head, gently pull forward tucking chin.',
    reps: '3×10',
    durationSeconds: 90,
    scorePoints: 3,
    targets: ['forward_head'],
    gifUrl: '/assets/exercises/towel-neck.gif',
  },
];
